services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: yo_reciclo
      MYSQL_ROOT_PASSWORD: "9029"
    ports: ["3307:3306"]
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  adminer:
    image: adminer
    ports: ["8080:8080"]
    depends_on: [db]

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "mysql://root:9029@db:3306/yo_reciclo"
      KEYCLOAK_URL: "http://keycloak:8081"
      KEYCLOAK_REALM: "yo-reciclo"
      KEYCLOAK_CLIENT_ID: "api-yo-reciclo"
      KEYCLOAK_CLIENT_SECRET: "UjGKTBJhTnApd6ABV4Jbbc5BPZMp34Lg"
    ports: ["3001:3000"]
    depends_on: [db, keycloak]
    volumes:
      - ../apps/backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    ports: ["4200:4200"]
    depends_on: [backend]
    volumes:
      - ../apps/frontend:/app
      - frontend_node_modules:/app/node_modules

  nginx:
    image: nginx:alpine
    ports: ["80:80"]
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: ["start-dev", "--http-port=8081", "--import-realm", "--hostname-url=http://keycloak:8081", "--hostname-strict=false"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8081:8081"]
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import:ro
    depends_on:
      - db


volumes:
  db_data:
  backend_node_modules:
  frontend_node_modules:
  keycloak_data: